//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public string Origin { get; set; }
        public string Destinations { get; set; }
        public int Route_Id { get; set; }
    }
}
